version: 2.1
orbs:
  gradle: circleci/gradle@1.0.11
jobs:
  upload:
    docker:
    - image: circleci/openjdk:8-jdk-node
    steps:
    - checkout
    - run:
        name: Create security ring
        command: echo -n "${SIGN_KEY}" | base64 --decode > secring
    - run:
        name: Upload artifacts
        command: ./gradlew uploadArchives
    - run:
        name: Close and Promote
        command: ./gradlew closeAndPromoteRepository --debug --stacktrace
workflows:
  test:
    jobs:
    - gradle/test:
        test_results_path: build/test_results/
        reports_path: build/reports
  release-artifacts:
    jobs:
    - build:
        filters:
          tags:
            only: /v[0-9]+\.[0-9]+\.[0-9]+/
    - upload:
        requires:
          - test
        filters:
          branches:
            only: /.*/
          tags:
            only: /v[0-9]+\.[0-9]+\.[0-9]+/

